### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by cneud** [impactcentre/interoperability-framework#17]
Currently not all Maven projects contain sufficient unit tests (or test coverage). Tests must be available for all individual modules and extended as appropriate where already available. Cobertura [[1]](http://cobertura.sourceforge.net/), [[2]](http://mojo.codehaus.org/cobertura-maven-plugin/) can be used to assess the percentage of the code accessed by tests.

**Comment by aeraln** [comment]
Done
